### ISSUE TITLE
Abierto a contribuciones?? 🤔

### ISSUE THREAD

**Issue by FranciscoJBrito** [CondorCoders/CRUD-js#1]
Hola Sofi 👋🏻.
Me gustaría saber si este proyecto esta abierto a contribuciones, para agregar algunas cosas como Vite,  React con TypeScript, y modularizar el código actual. Vi en tu canal que tienes un curso de Storybook, quizás también sea buena idea agregarlo para que tu comunidad pueda practicar colaborando en este repo.
Si te parece buena idea avísame, yo estaré encantado de colaborar.
Mas adelante también estaría bueno agregar algo de backend.

Saludos!!

**Comment by CondorCoders** [comment]
Hola Francisco! que buena idea, si quieres únete a la comunidad de Discord (link en mi perfil de Github) para hablar más y podemos hablar mejor. Tal vez hacer el repo de CRUDS en todos los frameworks, nose. También ya creé el repo para el curso de Storybook. Por ahora cada tema está separado en ramas pero abierta a sugerencias de como estructurarlo mejor.
